### ISSUE TITLE
https://apache.github.io/buildstream-plugins/ is pointing to old tag (1.91) instead current 1.95.1

### ISSUE THREAD

**Issue by jjardon** [apache/buildstream-plugins#32]

**Comment by gtristan** [comment]
Renaming issue which was previously:

> https://apache.github.io/buildstream-plugins/ is pointing to old tag (1.91) instead current 1.95.1

Some context:
* The https://apache.github.io/buildstream-plugins/ is displaying the correct documentation, which is generated from the latest push to `master`
* The documentation unfortunately advertises a version, this version is set at: https://github.com/apache/buildstream-plugins/blob/master/doc/source/conf.py#L65
* Since we only publish one version of the stable plugins, and will anyway need to add `Since x.y` annotations for newly added features in this repository, it seems unnecessary to advertise the version, it is always *"the latest"*
* It is also unlikely people will remember to update that version in the docs perfectly consistently, so it will be constantly at risk of being an incorrect version

Note that the version which is hardcoded in setup.py: https://github.com/apache/buildstream-plugins/blob/master/setup.py#L43 is also obnoxious to update with every tag and sometimes requires a re-tag at release time, at least in this case we end up remembering to update that hard coded version because we otherwise get an error uploading to `PyPI`.

An alternative would be to use `versioneer`, like BuildStream itself does.
